# Generated by Django 4.0 on 2021-12-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ativo',
        ),
    ]
