# Generated by Django 4.0 on 2021-12-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_remove_item_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thema',
            old_name='cor',
            new_name='color',
        ),
    ]
