# Generated by Django 4.0 on 2021-12-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_rename_cor_thema_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thema',
            new_name='Theme',
        ),
    ]
