# Generated by Django 3.2.7 on 2021-12-31 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_item_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='theme',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='rent.theme'),
        ),
    ]
