# Generated by Django 4.0 on 2021-12-31 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_alter_item_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='theme',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='rent.theme'),
        ),
    ]
